name: Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security:
    name: Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Bandit & Semgrep
        run: |
          python -m pip install --upgrade pip
          pip install bandit semgrep

      - name: Run Bandit Security Scan
        run: |
          bandit -r . --severity-level high -f json -o bandit-report.json || true

      - name: Run Semgrep Scan (Detect Flask SSTI)
        run: |
          semgrep --config "p/flask" --output semgrep-report.json || true

      - name: Upload Security Reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            bandit-report.json
            semgrep-report.json
