name: Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security-scan:
    name: Run Bandit & Semgrep Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install bandit semgrep

      - name: Run Bandit Security Scan (With Custom Plugin)
        run: bandit -r . --ini bandit.yaml | tee bandit-report.txt || true

      - name: Run Semgrep Security Scan
        run: semgrep --config semgrep.yaml --error --json > semgrep-report.json || true

      # ✅ Ensure the correct usage of `upload-artifact`
      - name: Upload Semgrep Report
        uses: actions/upload-artifact@v3
        with:
          name: semgrep-report
          path: semgrep-report.json

      - name: Upload Bandit Report
        uses: actions/upload-artifact@v3
        with:
          name: bandit-report
          path: bandit-report.txt
